"""
Configuration for the data ingestion pipeline.
"""

import os
from typing import Dict, Any
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# BigQuery Configuration
PROJECT_ID = os.getenv("DBT_PROJECT_ID")
DATASET = os.getenv("DBT_DATASET", "stripe_dev")
LOCATION = os.getenv("DBT_LOCATION", "US")
ENVIRONMENT = os.getenv("ENVIRONMENT", "development")
DBT_TARGET = os.getenv("DBT_TARGET", "dev")

# Paths
DATA_INPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "generate_stripe_data", "output")
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

# Validate required environment variables
if not PROJECT_ID:
    raise ValueError("DBT_PROJECT_ID environment variable is required")

if not GOOGLE_APPLICATION_CREDENTIALS:
    raise ValueError("GOOGLE_APPLICATION_CREDENTIALS environment variable is required")

# BigQuery table schemas for raw data
RAW_TABLE_SCHEMAS = {
    "customers": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "address", "type": "JSON", "mode": "NULLABLE"},
        {"name": "balance", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "currency", "type": "STRING", "mode": "NULLABLE"},
        {"name": "default_source", "type": "STRING", "mode": "NULLABLE"},
        {"name": "delinquent", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "description", "type": "STRING", "mode": "NULLABLE"},
        {"name": "discount", "type": "JSON", "mode": "NULLABLE"},
        {"name": "email", "type": "STRING", "mode": "NULLABLE"},
        {"name": "invoice_prefix", "type": "STRING", "mode": "NULLABLE"},
        {"name": "invoice_settings", "type": "JSON", "mode": "NULLABLE"},
        {"name": "livemode", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "metadata", "type": "JSON", "mode": "NULLABLE"},
        {"name": "name", "type": "STRING", "mode": "NULLABLE"},
        {"name": "next_invoice_sequence", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "phone", "type": "STRING", "mode": "NULLABLE"},
        {"name": "preferred_locales", "type": "STRING", "mode": "REPEATED"},
        {"name": "shipping", "type": "JSON", "mode": "NULLABLE"},
        {"name": "tax_exempt", "type": "STRING", "mode": "NULLABLE"},
        {"name": "test_clock", "type": "STRING", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "subscriptions": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "application", "type": "STRING", "mode": "NULLABLE"},
        {"name": "application_fee_percent", "type": "FLOAT", "mode": "NULLABLE"},
        {"name": "automatic_tax", "type": "JSON", "mode": "NULLABLE"},
        {"name": "billing_cycle_anchor", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "billing_thresholds", "type": "JSON", "mode": "NULLABLE"},
        {"name": "cancel_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "cancel_at_period_end", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "canceled_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "cancellation_details", "type": "JSON", "mode": "NULLABLE"},
        {"name": "collection_method", "type": "STRING", "mode": "NULLABLE"},
        {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "currency", "type": "STRING", "mode": "NULLABLE"},
        {"name": "current_period_end", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "current_period_start", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "customer", "type": "STRING", "mode": "NULLABLE"},
        {"name": "days_until_due", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "default_payment_method", "type": "STRING", "mode": "NULLABLE"},
        {"name": "default_source", "type": "STRING", "mode": "NULLABLE"},
        {"name": "default_tax_rates", "type": "JSON", "mode": "REPEATED"},
        {"name": "description", "type": "STRING", "mode": "NULLABLE"},
        {"name": "discount", "type": "JSON", "mode": "NULLABLE"},
        {"name": "ended_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "invoice_settings", "type": "JSON", "mode": "NULLABLE"},
        {"name": "items", "type": "JSON", "mode": "NULLABLE"},
        {"name": "latest_invoice", "type": "STRING", "mode": "NULLABLE"},
        {"name": "livemode", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "metadata", "type": "JSON", "mode": "NULLABLE"},
        {"name": "next_pending_invoice_item_invoice", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "on_behalf_of", "type": "STRING", "mode": "NULLABLE"},
        {"name": "pause_collection", "type": "JSON", "mode": "NULLABLE"},
        {"name": "payment_settings", "type": "JSON", "mode": "NULLABLE"},
        {"name": "pending_invoice_item_interval", "type": "JSON", "mode": "NULLABLE"},
        {"name": "pending_setup_intent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "pending_update", "type": "JSON", "mode": "NULLABLE"},
        {"name": "schedule", "type": "STRING", "mode": "NULLABLE"},
        {"name": "start_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "status", "type": "STRING", "mode": "NULLABLE"},
        {"name": "test_clock", "type": "STRING", "mode": "NULLABLE"},
        {"name": "transfer_data", "type": "JSON", "mode": "NULLABLE"},
        {"name": "trial_end", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "trial_settings", "type": "JSON", "mode": "NULLABLE"},
        {"name": "trial_start", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "invoices": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "account_country", "type": "STRING", "mode": "NULLABLE"},
        {"name": "account_name", "type": "STRING", "mode": "NULLABLE"},
        {"name": "account_tax_ids", "type": "JSON", "mode": "REPEATED"},
        {"name": "amount_due", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "amount_paid", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "amount_remaining", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "amount_shipping", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "application", "type": "STRING", "mode": "NULLABLE"},
        {"name": "application_fee_amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "attempt_count", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "attempted", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "auto_advance", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "automatic_tax", "type": "JSON", "mode": "NULLABLE"},
        {"name": "billing_reason", "type": "STRING", "mode": "NULLABLE"},
        {"name": "charge", "type": "STRING", "mode": "NULLABLE"},
        {"name": "collection_method", "type": "STRING", "mode": "NULLABLE"},
        {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "currency", "type": "STRING", "mode": "NULLABLE"},
        {"name": "custom_fields", "type": "JSON", "mode": "REPEATED"},
        {"name": "customer", "type": "STRING", "mode": "NULLABLE"},
        {"name": "customer_address", "type": "JSON", "mode": "NULLABLE"},
        {"name": "customer_email", "type": "STRING", "mode": "NULLABLE"},
        {"name": "customer_name", "type": "STRING", "mode": "NULLABLE"},
        {"name": "customer_phone", "type": "STRING", "mode": "NULLABLE"},
        {"name": "customer_shipping", "type": "JSON", "mode": "NULLABLE"},
        {"name": "customer_tax_exempt", "type": "STRING", "mode": "NULLABLE"},
        {"name": "customer_tax_ids", "type": "JSON", "mode": "REPEATED"},
        {"name": "default_payment_method", "type": "STRING", "mode": "NULLABLE"},
        {"name": "default_source", "type": "STRING", "mode": "NULLABLE"},
        {"name": "default_tax_rates", "type": "JSON", "mode": "REPEATED"},
        {"name": "description", "type": "STRING", "mode": "NULLABLE"},
        {"name": "discount", "type": "JSON", "mode": "NULLABLE"},
        {"name": "discounts", "type": "JSON", "mode": "REPEATED"},
        {"name": "due_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "effective_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "ending_balance", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "footer", "type": "STRING", "mode": "NULLABLE"},
        {"name": "from_invoice", "type": "JSON", "mode": "NULLABLE"},
        {"name": "hosted_invoice_url", "type": "STRING", "mode": "NULLABLE"},
        {"name": "invoice_pdf", "type": "STRING", "mode": "NULLABLE"},
        {"name": "issuer", "type": "JSON", "mode": "NULLABLE"},
        {"name": "last_finalization_error", "type": "JSON", "mode": "NULLABLE"},
        {"name": "latest_revision", "type": "STRING", "mode": "NULLABLE"},
        {"name": "lines", "type": "JSON", "mode": "NULLABLE"},
        {"name": "livemode", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "metadata", "type": "JSON", "mode": "NULLABLE"},
        {"name": "next_payment_attempt", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "number", "type": "STRING", "mode": "NULLABLE"},
        {"name": "on_behalf_of", "type": "STRING", "mode": "NULLABLE"},
        {"name": "paid", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "paid_out_of_band", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "payment_intent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "payment_settings", "type": "JSON", "mode": "NULLABLE"},
        {"name": "period_end", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "period_start", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "post_payment_credit_notes_amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "pre_payment_credit_notes_amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "quote", "type": "STRING", "mode": "NULLABLE"},
        {"name": "receipt_number", "type": "STRING", "mode": "NULLABLE"},
        {"name": "rendering", "type": "JSON", "mode": "NULLABLE"},
        {"name": "rendering_options", "type": "JSON", "mode": "NULLABLE"},
        {"name": "shipping_cost", "type": "JSON", "mode": "NULLABLE"},
        {"name": "shipping_details", "type": "JSON", "mode": "NULLABLE"},
        {"name": "starting_balance", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "statement_descriptor", "type": "STRING", "mode": "NULLABLE"},
        {"name": "status", "type": "STRING", "mode": "NULLABLE"},
        {"name": "status_transitions", "type": "JSON", "mode": "NULLABLE"},
        {"name": "subscription", "type": "STRING", "mode": "NULLABLE"},
        {"name": "subscription_details", "type": "JSON", "mode": "NULLABLE"},
        {"name": "subscription_proration_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "subtotal", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "subtotal_excluding_tax", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "tax", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "test_clock", "type": "STRING", "mode": "NULLABLE"},
        {"name": "total", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "total_discount_amounts", "type": "JSON", "mode": "REPEATED"},
        {"name": "total_excluding_tax", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "total_tax_amounts", "type": "JSON", "mode": "REPEATED"},
        {"name": "transfer_data", "type": "JSON", "mode": "NULLABLE"},
        {"name": "webhooks_delivered_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "products": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "active", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "default_price", "type": "STRING", "mode": "NULLABLE"},
        {"name": "description", "type": "STRING", "mode": "NULLABLE"},
        {"name": "features", "type": "JSON", "mode": "REPEATED"},
        {"name": "images", "type": "STRING", "mode": "REPEATED"},
        {"name": "livemode", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "metadata", "type": "JSON", "mode": "NULLABLE"},
        {"name": "name", "type": "STRING", "mode": "NULLABLE"},
        {"name": "package_dimensions", "type": "JSON", "mode": "NULLABLE"},
        {"name": "shippable", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "statement_descriptor", "type": "STRING", "mode": "NULLABLE"},
        {"name": "tax_code", "type": "STRING", "mode": "NULLABLE"},
        {"name": "type", "type": "STRING", "mode": "NULLABLE"},
        {"name": "unit_label", "type": "STRING", "mode": "NULLABLE"},
        {"name": "updated", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "url", "type": "STRING", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "prices": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "active", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "billing_scheme", "type": "STRING", "mode": "NULLABLE"},
        {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "currency", "type": "STRING", "mode": "NULLABLE"},
        {"name": "currency_options", "type": "JSON", "mode": "NULLABLE"},
        {"name": "custom_unit_amount", "type": "JSON", "mode": "NULLABLE"},
        {"name": "livemode", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "lookup_key", "type": "STRING", "mode": "NULLABLE"},
        {"name": "metadata", "type": "JSON", "mode": "NULLABLE"},
        {"name": "nickname", "type": "STRING", "mode": "NULLABLE"},
        {"name": "product", "type": "STRING", "mode": "NULLABLE"},
        {"name": "recurring", "type": "JSON", "mode": "NULLABLE"},
        {"name": "tax_behavior", "type": "STRING", "mode": "NULLABLE"},
        {"name": "tiers", "type": "JSON", "mode": "REPEATED"},
        {"name": "tiers_mode", "type": "STRING", "mode": "NULLABLE"},
        {"name": "transform_quantity", "type": "JSON", "mode": "NULLABLE"},
        {"name": "type", "type": "STRING", "mode": "NULLABLE"},
        {"name": "unit_amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "unit_amount_decimal", "type": "STRING", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "payment_methods": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "allow_redisplay", "type": "STRING", "mode": "NULLABLE"},
        {"name": "billing_details", "type": "JSON", "mode": "NULLABLE"},
        {"name": "card", "type": "JSON", "mode": "NULLABLE"},
        {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "customer", "type": "STRING", "mode": "NULLABLE"},
        {"name": "livemode", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "metadata", "type": "JSON", "mode": "NULLABLE"},
        {"name": "type", "type": "STRING", "mode": "NULLABLE"},
        {"name": "us_bank_account", "type": "JSON", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "refunds": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "balance_transaction", "type": "STRING", "mode": "NULLABLE"},
        {"name": "charge", "type": "STRING", "mode": "NULLABLE"},
        {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "currency", "type": "STRING", "mode": "NULLABLE"},
        {"name": "description", "type": "STRING", "mode": "NULLABLE"},
        {"name": "destination_details", "type": "JSON", "mode": "NULLABLE"},
        {"name": "failure_balance_transaction", "type": "STRING", "mode": "NULLABLE"},
        {"name": "failure_reason", "type": "STRING", "mode": "NULLABLE"},
        {"name": "instructions_email", "type": "STRING", "mode": "NULLABLE"},
        {"name": "metadata", "type": "JSON", "mode": "NULLABLE"},
        {"name": "next_action", "type": "JSON", "mode": "NULLABLE"},
        {"name": "payment_intent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "reason", "type": "STRING", "mode": "NULLABLE"},
        {"name": "receipt_number", "type": "STRING", "mode": "NULLABLE"},
        {"name": "source_transfer_reversal", "type": "STRING", "mode": "NULLABLE"},
        {"name": "status", "type": "STRING", "mode": "NULLABLE"},
        {"name": "transfer_reversal", "type": "STRING", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "disputes": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "balance_transactions", "type": "JSON", "mode": "REPEATED"},
        {"name": "charge", "type": "STRING", "mode": "NULLABLE"},
        {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "currency", "type": "STRING", "mode": "NULLABLE"},
        {"name": "evidence", "type": "JSON", "mode": "NULLABLE"},
        {"name": "evidence_details", "type": "JSON", "mode": "NULLABLE"},
        {"name": "is_charge_refundable", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "livemode", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "metadata", "type": "JSON", "mode": "NULLABLE"},
        {"name": "network_reason_code", "type": "STRING", "mode": "NULLABLE"},
        {"name": "payment_intent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "payment_method_details", "type": "JSON", "mode": "NULLABLE"},
        {"name": "reason", "type": "STRING", "mode": "NULLABLE"},
        {"name": "status", "type": "STRING", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "charges": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "amount_captured", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "amount_refunded", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "application", "type": "STRING", "mode": "NULLABLE"},
        {"name": "application_fee", "type": "STRING", "mode": "NULLABLE"},
        {"name": "application_fee_amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "balance_transaction", "type": "STRING", "mode": "NULLABLE"},
        {"name": "billing_details", "type": "JSON", "mode": "NULLABLE"},
        {"name": "calculated_statement_descriptor", "type": "STRING", "mode": "NULLABLE"},
        {"name": "captured", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "currency", "type": "STRING", "mode": "NULLABLE"},
        {"name": "customer", "type": "STRING", "mode": "NULLABLE"},
        {"name": "description", "type": "STRING", "mode": "NULLABLE"},
        {"name": "destination", "type": "STRING", "mode": "NULLABLE"},
        {"name": "dispute", "type": "STRING", "mode": "NULLABLE"},
        {"name": "disputed", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "failure_balance_transaction", "type": "STRING", "mode": "NULLABLE"},
        {"name": "failure_code", "type": "STRING", "mode": "NULLABLE"},
        {"name": "failure_message", "type": "STRING", "mode": "NULLABLE"},
        {"name": "fraud_details", "type": "JSON", "mode": "NULLABLE"},
        {"name": "invoice", "type": "STRING", "mode": "NULLABLE"},
        {"name": "livemode", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "metadata", "type": "JSON", "mode": "NULLABLE"},
        {"name": "on_behalf_of", "type": "STRING", "mode": "NULLABLE"},
        {"name": "order", "type": "STRING", "mode": "NULLABLE"},
        {"name": "outcome", "type": "JSON", "mode": "NULLABLE"},
        {"name": "paid", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "payment_intent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "payment_method", "type": "STRING", "mode": "NULLABLE"},
        {"name": "payment_method_details", "type": "JSON", "mode": "NULLABLE"},
        {"name": "receipt_email", "type": "STRING", "mode": "NULLABLE"},
        {"name": "receipt_number", "type": "STRING", "mode": "NULLABLE"},
        {"name": "receipt_url", "type": "STRING", "mode": "NULLABLE"},
        {"name": "refunded", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "refunds", "type": "JSON", "mode": "NULLABLE"},
        {"name": "review", "type": "STRING", "mode": "NULLABLE"},
        {"name": "shipping", "type": "JSON", "mode": "NULLABLE"},
        {"name": "source", "type": "JSON", "mode": "NULLABLE"},
        {"name": "source_transfer", "type": "STRING", "mode": "NULLABLE"},
        {"name": "statement_descriptor", "type": "STRING", "mode": "NULLABLE"},
        {"name": "statement_descriptor_suffix", "type": "STRING", "mode": "NULLABLE"},
        {"name": "status", "type": "STRING", "mode": "NULLABLE"},
        {"name": "transfer_data", "type": "JSON", "mode": "NULLABLE"},
        {"name": "transfer_group", "type": "STRING", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "customer_balance_transactions": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "credit_note", "type": "STRING", "mode": "NULLABLE"},
        {"name": "currency", "type": "STRING", "mode": "NULLABLE"},
        {"name": "customer", "type": "STRING", "mode": "NULLABLE"},
        {"name": "description", "type": "STRING", "mode": "NULLABLE"},
        {"name": "ending_balance", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "invoice", "type": "STRING", "mode": "NULLABLE"},
        {"name": "livemode", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "metadata", "type": "JSON", "mode": "NULLABLE"},
        {"name": "type", "type": "STRING", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "credit_notes": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "amount_shipping", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "currency", "type": "STRING", "mode": "NULLABLE"},
        {"name": "customer", "type": "STRING", "mode": "NULLABLE"},
        {"name": "customer_balance_transaction", "type": "STRING", "mode": "NULLABLE"},
        {"name": "discount_amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "discount_amounts", "type": "JSON", "mode": "REPEATED"},
        {"name": "effective_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "invoice", "type": "STRING", "mode": "NULLABLE"},
        {"name": "lines", "type": "JSON", "mode": "NULLABLE"},
        {"name": "livemode", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "memo", "type": "STRING", "mode": "NULLABLE"},
        {"name": "metadata", "type": "JSON", "mode": "NULLABLE"},
        {"name": "number", "type": "STRING", "mode": "NULLABLE"},
        {"name": "out_of_band_amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "pdf", "type": "STRING", "mode": "NULLABLE"},
        {"name": "reason", "type": "STRING", "mode": "NULLABLE"},
        {"name": "refund", "type": "STRING", "mode": "NULLABLE"},
        {"name": "shipping_cost", "type": "JSON", "mode": "NULLABLE"},
        {"name": "status", "type": "STRING", "mode": "NULLABLE"},
        {"name": "subtotal", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "subtotal_excluding_tax", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "tax_amounts", "type": "JSON", "mode": "REPEATED"},
        {"name": "total", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "total_excluding_tax", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "type", "type": "STRING", "mode": "NULLABLE"},
        {"name": "voided_at", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "invoice_items": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "currency", "type": "STRING", "mode": "NULLABLE"},
        {"name": "customer", "type": "STRING", "mode": "NULLABLE"},
        {"name": "date", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "description", "type": "STRING", "mode": "NULLABLE"},
        {"name": "discountable", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "discounts", "type": "JSON", "mode": "REPEATED"},
        {"name": "invoice", "type": "STRING", "mode": "NULLABLE"},
        {"name": "livemode", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "metadata", "type": "JSON", "mode": "NULLABLE"},
        {"name": "period", "type": "JSON", "mode": "NULLABLE"},
        {"name": "price", "type": "JSON", "mode": "NULLABLE"},
        {"name": "proration", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "quantity", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "subscription", "type": "STRING", "mode": "NULLABLE"},
        {"name": "tax_rates", "type": "JSON", "mode": "REPEATED"},
        {"name": "test_clock", "type": "STRING", "mode": "NULLABLE"},
        {"name": "unit_amount", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "unit_amount_decimal", "type": "STRING", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "tax_ids": [
        {"name": "id", "type": "STRING", "mode": "REQUIRED"},
        {"name": "object", "type": "STRING", "mode": "NULLABLE"},
        {"name": "country", "type": "STRING", "mode": "NULLABLE"},
        {"name": "created", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "customer", "type": "STRING", "mode": "NULLABLE"},
        {"name": "livemode", "type": "BOOLEAN", "mode": "NULLABLE"},
        {"name": "type", "type": "STRING", "mode": "NULLABLE"},
        {"name": "value", "type": "STRING", "mode": "NULLABLE"},
        {"name": "verification", "type": "JSON", "mode": "NULLABLE"},
        {"name": "_ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "_updated_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
}

# Logging configuration
LOGGING_CONFIG = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
        },
    },
    "handlers": {
        "default": {
            "level": "INFO",
            "formatter": "standard",
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "": {
            "handlers": ["default"],
            "level": "INFO",
            "propagate": False
        }
    }
} 